# Generated by Django 3.2.4 on 2021-06-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaRemision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_guia', models.IntegerField()),
                ('punto_par', models.CharField(max_length=50)),
                ('punto_lle', models.CharField(max_length=50)),
                ('fecha_traslado', models.DateField()),
                ('costo_min', models.IntegerField()),
                ('nom_empresa_transportes', models.CharField(max_length=100)),
                ('ruc_empresa_transportes', models.CharField(max_length=50)),
                ('marca_num_placa', models.CharField(max_length=50)),
                ('nro_cons_inscripcion', models.CharField(max_length=50)),
                ('nro_lic_conductor', models.CharField(max_length=50)),
                ('tipo_num_comp_pago', models.CharField(max_length=50)),
                ('orden_compra', models.CharField(max_length=50)),
                ('cliente', models.IntegerField()),
            ],
            options={
                'db_table': 'guia_remision',
                'managed': False,
            },
        ),
    ]
